package gohpts

import (
	"testing"

	"github.com/stretchr/testify/require"
)

func TestNewProxyErr(t *testing.T) {
	t.Parallel()
	testcases := []struct {
		name   string
		config *Config
		errMsg string
	}{
		{
			name: "logfile",
			config: &Config{
				AddrHTTP:      "127.0.0.1:8080",
				ServerUser:    "user",
				ServerPass:    "secret",
				SocksProxy:    []ProxyEntry{{Address: addrSOCKS, Username: "user", Password: "password"}},
				Interface:     "wlan0",
				IPv4Enabled:   true,
				IPv6Enabled:   true,
				TProxyMode:    "tproxy",
				TProxy:        "0.0.0.0:8888",
				TProxyWorkers: 1,
				TProxyUDP:     "0.0.0.0:8889",
				NoHTTP:        true,
				Auto:          false,
				Dump:          false,
				Mark:          69,
				IgnoredPorts:  "22,443",
				Debug:         true,
				LogFilePath:   "/var/log/gohtps.log",
				AddrPprof:     "127.0.0.1:6060",
				Sniff:         true,
				Body:          true,
				ARPSpoof:      "targets 192.168.10.0/24;fullduplex true;debug true;interval 10s",
				NDPSpoof:      "ra true;debug true;prefix 2001:db8:7a31:4400::/64;router_lifetime 30s;interval 10s;mtu 1500;packet HRD F2 DSDS",
			},
			errMsg: "failed to open log file: open /var/log/gohtps.log: permission denied",
		},
		{
			name: "sniff logfile",
			config: &Config{
				AddrHTTP:      "127.0.0.1:8080",
				ServerUser:    "user",
				ServerPass:    "secret",
				SocksProxy:    []ProxyEntry{{Address: addrSOCKS, Username: "user", Password: "password"}},
				Interface:     "wlan0",
				IPv4Enabled:   true,
				IPv6Enabled:   true,
				TProxyMode:    "tproxy",
				TProxy:        "0.0.0.0:8888",
				TProxyWorkers: 1,
				TProxyUDP:     "0.0.0.0:8889",
				NoHTTP:        true,
				Auto:          false,
				Dump:          false,
				Mark:          69,
				IgnoredPorts:  "22,443",
				Debug:         true,
				AddrPprof:     "127.0.0.1:6060",
				Sniff:         true,
				Body:          true,
				SniffLogFile:  "/var/log/gohpts_sniff.log",
				ARPSpoof:      "targets 192.168.10.0/24;fullduplex true;debug true;interval 10s",
				NDPSpoof:      "ra true;debug true;prefix 2001:db8:7a31:4400::/64;router_lifetime 30s;interval 10s;mtu 1500;packet HRD F2 DSDS",
			},
			errMsg: "failed to open sniff log file: open /var/log/gohpts_sniff.log: permission denied",
		},
		{
			name: "unknown transparent proxy mode",
			config: &Config{
				AddrHTTP:      "127.0.0.1:8080",
				ServerUser:    "user",
				ServerPass:    "secret",
				SocksProxy:    []ProxyEntry{{Address: addrSOCKS, Username: "user", Password: "password"}},
				Interface:     "wlan0",
				IPv4Enabled:   true,
				IPv6Enabled:   true,
				TProxyMode:    "test",
				TProxy:        "0.0.0.0:8888",
				TProxyWorkers: 1,
				TProxyUDP:     "0.0.0.0:8889",
				NoHTTP:        true,
				Auto:          false,
				Dump:          false,
				Mark:          69,
				IgnoredPorts:  "22,443",
				Debug:         true,
				AddrPprof:     "127.0.0.1:6060",
				Sniff:         true,
				Body:          true,
				ARPSpoof:      "targets 192.168.10.0/24;fullduplex true;debug true;interval 10s",
				NDPSpoof:      "ra true;debug true;prefix 2001:db8:7a31:4400::/64;router_lifetime 30s;interval 10s;mtu 1500;packet HRD F2 DSDS",
			},
			errMsg: "unknown transparent proxy mode: test",
		},
		{
			name: "udp transparent proxy with malformed mode",
			config: &Config{
				AddrHTTP:      "127.0.0.1:8080",
				ServerUser:    "user",
				ServerPass:    "secret",
				SocksProxy:    []ProxyEntry{{Address: addrSOCKS, Username: "user", Password: "password"}},
				Interface:     "wlan0",
				IPv4Enabled:   true,
				IPv6Enabled:   true,
				TProxyMode:    "redirect",
				TProxy:        "0.0.0.0:8888",
				TProxyWorkers: 1,
				TProxyUDP:     "0.0.0.0:8889",
				NoHTTP:        true,
				Auto:          false,
				Dump:          false,
				Mark:          69,
				IgnoredPorts:  "22,443",
				Debug:         true,
				AddrPprof:     "127.0.0.1:6060",
				Sniff:         true,
				Body:          true,
				ARPSpoof:      "targets 192.168.10.0/24;fullduplex true;debug true;interval 10s",
				NDPSpoof:      "ra true;debug true;prefix 2001:db8:7a31:4400::/64;router_lifetime 30s;interval 10s;mtu 1500;packet HRD F2 DSDS",
			},
			errMsg: "[redirect] transparent UDP server only supports tproxy or tlocal mode",
		},
		{
			name: "auto requires root",
			config: &Config{
				AddrHTTP:      "127.0.0.1:8080",
				ServerUser:    "user",
				ServerPass:    "secret",
				SocksProxy:    []ProxyEntry{{Address: addrSOCKS, Username: "user", Password: "password"}},
				Interface:     "wlan0",
				IPv4Enabled:   true,
				IPv6Enabled:   true,
				TProxyMode:    "tproxy",
				TProxy:        "0.0.0.0:8888",
				TProxyWorkers: 1,
				TProxyUDP:     "0.0.0.0:8889",
				NoHTTP:        true,
				Auto:          true,
				Dump:          true,
				Mark:          69,
				IgnoredPorts:  "22,443",
				Debug:         true,
				AddrPprof:     "127.0.0.1:6060",
				Sniff:         true,
				Body:          true,
				ARPSpoof:      "targets 192.168.10.0/24;fullduplex true;debug true;interval 10s",
				NDPSpoof:      "ra true;debug true;prefix 2001:db8:7a31:4400::/64;router_lifetime 30s;interval 10s;mtu 1500;packet HRD F2 DSDS",
			},
			errMsg: "auto configuration requires root privileges",
		},
		{
			name: "dump requires auto",
			config: &Config{
				AddrHTTP:      "127.0.0.1:8080",
				ServerUser:    "user",
				ServerPass:    "secret",
				SocksProxy:    []ProxyEntry{{Address: addrSOCKS, Username: "user", Password: "password"}},
				Interface:     "wlan0",
				IPv4Enabled:   true,
				IPv6Enabled:   true,
				TProxyMode:    "tproxy",
				TProxy:        "0.0.0.0:8888",
				TProxyWorkers: 1,
				TProxyUDP:     "0.0.0.0:8889",
				NoHTTP:        true,
				Dump:          true,
				Mark:          69,
				IgnoredPorts:  "22,443",
				Debug:         true,
				AddrPprof:     "127.0.0.1:6060",
				Sniff:         true,
				Body:          true,
				ARPSpoof:      "targets 192.168.10.0/24;fullduplex true;debug true;interval 10s",
				NDPSpoof:      "ra true;debug true;prefix 2001:db8:7a31:4400::/64;router_lifetime 30s;interval 10s;mtu 1500;packet HRD F2 DSDS",
			},
			errMsg: "dumping rules is only possible in auto configuration",
		},
		{
			name: "mark out of range",
			config: &Config{
				AddrHTTP:      "127.0.0.1:8080",
				ServerUser:    "user",
				ServerPass:    "secret",
				SocksProxy:    []ProxyEntry{{Address: addrSOCKS, Username: "user", Password: "password"}},
				Interface:     "wlan0",
				IPv4Enabled:   true,
				IPv6Enabled:   true,
				TProxyMode:    "tproxy",
				TProxy:        "0.0.0.0:8888",
				TProxyWorkers: 1,
				TProxyUDP:     "0.0.0.0:8889",
				NoHTTP:        true,
				Mark:          0xFFFFFFFFFF,
				IgnoredPorts:  "22,443",
				Debug:         true,
				AddrPprof:     "127.0.0.1:6060",
				Sniff:         true,
				Body:          true,
				ARPSpoof:      "targets 192.168.10.0/24;fullduplex true;debug true;interval 10s",
				NDPSpoof:      "ra true;debug true;prefix 2001:db8:7a31:4400::/64;router_lifetime 30s;interval 10s;mtu 1500;packet HRD F2 DSDS",
			},
			errMsg: "option SO_MARK is out of range",
		},
		{
			name: "ignoring ports no auto",
			config: &Config{
				AddrHTTP:      "127.0.0.1:8080",
				ServerUser:    "user",
				ServerPass:    "secret",
				SocksProxy:    []ProxyEntry{{Address: addrSOCKS, Username: "user", Password: "password"}},
				Interface:     "wlan0",
				IPv4Enabled:   true,
				IPv6Enabled:   true,
				TProxyMode:    "tproxy",
				TProxy:        "0.0.0.0:8888",
				TProxyWorkers: 1,
				TProxyUDP:     "0.0.0.0:8889",
				NoHTTP:        true,
				Mark:          69,
				IgnoredPorts:  "22,443",
				Debug:         true,
				AddrPprof:     "127.0.0.1:6060",
				Sniff:         true,
				Body:          true,
				ARPSpoof:      "targets 192.168.10.0/24;fullduplex true;debug true;interval 10s",
				NDPSpoof:      "ra true;debug true;prefix 2001:db8:7a31:4400::/64;router_lifetime 30s;interval 10s;mtu 1500;packet HRD F2 DSDS",
			},
			errMsg: "ignoring ports is only possible in auto configuration",
		},
		{
			name: "socks4 enabled",
			config: &Config{
				AddrHTTP:      "127.0.0.1:8080",
				ServerUser:    "user",
				ServerPass:    "secret",
				SocksProxy:    []ProxyEntry{{Address: addrSOCKS, Username: "user", Password: "password"}},
				Interface:     "wlan0",
				IPv4Enabled:   true,
				IPv6Enabled:   true,
				SOCKS4Enabled: true,
				TProxyMode:    "tproxy",
				TProxy:        "0.0.0.0:8888",
				TProxyWorkers: 1,
				TProxyUDP:     "0.0.0.0:8889",
				NoHTTP:        true,
				Auto:          false,
				Dump:          false,
				Mark:          69,
				Debug:         true,
				AddrPprof:     "127.0.1:6060",
				Sniff:         true,
				Body:          true,
				ARPSpoof:      "targets 192.168.10.0/24;fullduplex true;debug true;interval 10s",
				NDPSpoof:      "ra true;debug true;prefix 2001:db8:7a31:4400::/64;router_lifetime 30s;interval 10s;mtu 1500;packet HRD F2 DSDS",
			},
			errMsg: `[tproxy] transparent UDP server requires socks5 enabled`,
		},
		{
			name: "malformed proxy chain type",
			config: &Config{
				AddrHTTP:       "127.0.0.1:8080",
				ServerUser:     "user",
				ServerPass:     "secret",
				Interface:      "wlan0",
				ServerConfPath: "testdata/config_malformed_chaintype.yaml",
				IPv4Enabled:    true,
				IPv6Enabled:    true,
				TProxyMode:     "tproxy",
				TProxy:         "0.0.0.0:8888",
				TProxyWorkers:  1,
				TProxyUDP:      "0.0.0.0:8889",
				NoHTTP:         true,
				Mark:           69,
				Debug:          true,
				AddrPprof:      "127.0.0.1:6060",
				Sniff:          true,
				Body:           true,
				ARPSpoof:       "targets 192.168.10.0/24;fullduplex true;debug true;interval 10s",
				NDPSpoof:       "ra true;debug true;prefix 2001:db8:7a31:4400::/64;router_lifetime 30s;interval 10s;mtu 1500;packet HRD F2 DSDS",
			},
			errMsg: "chain type `test` is not supported",
		},
		{
			name: "dns server IPv6 with IPv6 disabled",
			config: &Config{
				IPv4Enabled: true,
				IPv6Enabled: false,
				DNS:         "2001:4860:4860::8844",
			},
			errMsg: "enable IPv6 to use dns server address 2001:4860:4860::8844",
		},
		{
			name: "ipv4 address in ipv6 mode",
			config: &Config{
				AddrHTTP:       "127.0.0.1:8080",
				ServerUser:     "user",
				ServerPass:     "secret",
				Interface:      "wlan0",
				ServerConfPath: "testdata/config_proxy_list_duplicate.yaml",
				IPv6Enabled:    true,
				TProxyMode:     "tproxy",
				TProxy:         "0.0.0.0:8888",
				TProxyWorkers:  1,
				TProxyUDP:      "0.0.0.0:8889",
				NoHTTP:         true,
				Mark:           69,
				Debug:          true,
				AddrPprof:      "127.0.0.1:6060",
				Sniff:          true,
				Body:           true,
				ARPSpoof:       "targets 192.168.10.0/24;fullduplex true;debug true;interval 10s",
				NDPSpoof:       "ra true;debug true;prefix 2001:db8:7a31:4400::/64;router_lifetime 30s;interval 10s;mtu 1500;packet HRD F2 DSDS",
			},
			errMsg: "enable IPv4 to bind transparent proxy to 0.0.0.0:8888",
		},
		{
			name: "ipv4 address in ipv6 mode 1",
			config: &Config{
				AddrHTTP:       "127.0.0.1:8080",
				ServerUser:     "user",
				ServerPass:     "secret",
				Interface:      "wlan0",
				ServerConfPath: "testdata/config_proxy_list_duplicate.yaml",
				IPv6Enabled:    true,
				TProxyMode:     "tproxy",
				TProxy:         ":8888",
				TProxyWorkers:  1,
				TProxyUDP:      "0.0.0.0:8889",
				NoHTTP:         true,
				Mark:           69,
				Debug:          true,
				AddrPprof:      "127.0.0.1:6060",
				Sniff:          true,
				Body:           true,
				ARPSpoof:       "targets 192.168.10.0/24;fullduplex true;debug true;interval 10s",
				NDPSpoof:       "ra true;debug true;prefix 2001:db8:7a31:4400::/64;router_lifetime 30s;interval 10s;mtu 1500;packet HRD F2 DSDS",
			},
			errMsg: "enable IPv4 to bind transparent proxy to 0.0.0.0:8889",
		},
		{
			name: "ipv4 address in ipv6 mode 2",
			config: &Config{
				AddrHTTP:       "127.0.0.1:8080",
				ServerUser:     "user",
				ServerPass:     "secret",
				Interface:      "wlan0",
				ServerConfPath: "testdata/config_proxy_list_duplicate.yaml",
				IPv6Enabled:    true,
				TProxyMode:     "tproxy",
				TProxy:         ":8888",
				TProxyWorkers:  1,
				TProxyUDP:      ":8889",
				DNS:            "8.8.8.8",
				NoHTTP:         true,
				Mark:           69,
				Debug:          true,
				AddrPprof:      "127.0.0.1:6060",
				Sniff:          true,
				Body:           true,
				ARPSpoof:       "targets 192.168.10.0/24;fullduplex true;debug true;interval 10s",
				NDPSpoof:       "ra true;debug true;prefix 2001:db8:7a31:4400::/64;router_lifetime 30s;interval 10s;mtu 1500;packet HRD F2 DSDS",
			},
			errMsg: "enable IPv4 to use dns server address 8.8.8.8",
		},
	}
	for _, testcase := range testcases {
		t.Run(testcase.name, func(t *testing.T) {
			_, err := New(testcase.config)
			require.EqualError(t, err, testcase.errMsg)
		})
	}
}

func TestRunProxyErr(t *testing.T) {
	t.Parallel()
	testcases := []struct {
		name   string
		config *Config
		errMsg string
	}{
		{
			name: "malformed pprof address",
			config: &Config{
				AddrHTTP:      "127.0.0.1:8080",
				ServerUser:    "user",
				ServerPass:    "secret",
				SocksProxy:    []ProxyEntry{{Address: addrSOCKS, Username: "user", Password: "password"}},
				Interface:     "wlan0",
				IPv4Enabled:   true,
				IPv6Enabled:   true,
				TProxyMode:    "tproxy",
				TProxy:        "0.0.0.0:8888",
				TProxyWorkers: 1,
				TProxyUDP:     "0.0.0.0:8889",
				NoHTTP:        true,
				Auto:          false,
				Dump:          false,
				Mark:          69,
				Debug:         true,
				AddrPprof:     "127.0.1:6060",
				Sniff:         true,
				Body:          true,
				ARPSpoof:      "targets 192.168.10.0/24;fullduplex true;debug true;interval 10s",
				NDPSpoof:      "ra true;debug true;prefix 2001:db8:7a31:4400::/64;router_lifetime 30s;interval 10s;mtu 1500;packet HRD F2 DSDS",
			},
			errMsg: `ParseAddr("127.0.1"): IPv4 address too short`,
		},
		{
			name: "proxy list duplicate",
			config: &Config{
				AddrHTTP:       "127.0.0.1:8080",
				ServerUser:     "user",
				ServerPass:     "secret",
				Interface:      "wlan0",
				ServerConfPath: "testdata/config_proxy_list_duplicate.yaml",
				IPv4Enabled:    true,
				IPv6Enabled:    true,
				TProxyMode:     "tproxy",
				TProxy:         "0.0.0.0:8888",
				TProxyWorkers:  1,
				TProxyUDP:      "0.0.0.0:8889",
				NoHTTP:         true,
				Mark:           69,
				Debug:          true,
				AddrPprof:      "127.0.0.1:6060",
				Sniff:          true,
				Body:           true,
			},
			errMsg: "proxy list duplicate entry `127.0.0.1:1080`",
		},
		{
			name: "ipv4 address in ipv6 mode 3",
			config: &Config{
				AddrHTTP:      "127.0.0.1:8080",
				ServerUser:    "user",
				ServerPass:    "secret",
				Interface:     "wlan0",
				IPv6Enabled:   true,
				TProxyMode:    "tproxy",
				TProxy:        "[::]:8888",
				TProxyWorkers: 1,
				TProxyUDP:     "[::]:8889",
				NoHTTP:        true,
				Mark:          69,
				Debug:         true,
				AddrPprof:     "127.0.0.1:6060",
				Sniff:         true,
				Body:          true,
				ARPSpoof:      "targets 192.168.10.0/24;fullduplex true;debug true;interval 10s",
				NDPSpoof:      "ra true;debug true;prefix 2001:db8:7a31:4400::/64;router_lifetime 30s;interval 10s;mtu 1500;packet HRD F2 DSDS",
			},
			errMsg: "enable IPv4 to bind PPROF server to 127.0.0.1:6060",
		},
		{
			name: "ipv4 address in ipv6 mode 4",
			config: &Config{
				AddrHTTP:      "127.0.0.1:8081",
				ServerUser:    "user",
				ServerPass:    "secret",
				Interface:     "wlan0",
				IPv6Enabled:   true,
				TProxyMode:    "tproxy",
				TProxy:        "[::1]:8888",
				TProxyWorkers: 1,
				TProxyUDP:     "[::1]:8889",
				NoHTTP:        false,
				Mark:          69,
				Debug:         true,
				AddrPprof:     ":6060",
				Sniff:         true,
				Body:          true,
			},
			errMsg: "enable IPv4 to use 127.0.0.1:8081 for http server",
		},
		{
			name: "ipv4 address in ipv6 mode 5",
			config: &Config{
				SocksProxy:    []ProxyEntry{{Address: addrSOCKS}},
				ServerUser:    "user",
				ServerPass:    "secret",
				Interface:     "wlan0",
				IPv6Enabled:   true,
				TProxyMode:    "tproxy",
				TProxy:        "[::1]:8888",
				TProxyWorkers: 1,
				TProxyUDP:     "[::1]:8889",
				NoHTTP:        false,
				Mark:          69,
				Debug:         true,
				AddrPprof:     ":6060",
				Sniff:         true,
				Body:          true,
			},
			errMsg: "enable IPv4 to use 127.0.0.1:1080 for upstream SOCKS",
		},
		{
			name: "ipv6 address in ipv4 mode",
			config: &Config{
				SocksProxy:    []ProxyEntry{{Address: addr6SOCKS}},
				ServerUser:    "user",
				ServerPass:    "secret",
				Interface:     "wlan0",
				IPv4Enabled:   true,
				IPv6Enabled:   false,
				TProxyMode:    "tproxy",
				TProxy:        ":8888",
				TProxyWorkers: 1,
				TProxyUDP:     ":8889",
				NoHTTP:        false,
				Mark:          69,
				Debug:         true,
				AddrPprof:     ":6060",
				Sniff:         true,
				Body:          true,
			},
			errMsg: "enable IPv6 to use [::1]:1080 for upstream SOCKS",
		},
	}
	for _, testcase := range testcases {
		t.Run(testcase.name, func(t *testing.T) {
			p, err := New(testcase.config)
			require.NoError(t, err)
			err = p.Run()
			require.EqualError(t, err, testcase.errMsg)
		})
	}
}
