package main

import (
	"flag"
	"fmt"
	"os"
	"runtime"
	"slices"

	gohpts "github.com/shadowy-pycoder/go-http-proxy-to-socks"
	"github.com/shadowy-pycoder/mshark/network"
	"golang.org/x/term"
)

const usagePrefix string = `   _____       _    _ _____ _______ _____
  / ____|     | |  | |  __ \__   __/ ____|
 | |  __  ___ | |__| | |__) | | | | (___
 | | |_ |/ _ \|  __  |  ___/  | |  \___ \
 | |__| | (_) | |  | | |      | |  ____) |
  \_____|\___/|_|  |_|_|      |_| |_____/

GoHPTS (HTTP(S) Proxy to SOCKS4/SOCKS5 proxy) by shadowy-pycoder
GitHub: https://github.com/shadowy-pycoder/go-http-proxy-to-socks
Codeberg: https://codeberg.org/shadowy-pycoder/go-http-proxy-to-socks

Usage: gohpts [OPTIONS]
OPTIONS:
  General:
  -h         Show this help message and exit
  -v         Show version and build information
  -D         Run as a daemon (provide -logfile to see logs)
  -I         Display list of network interfaces and exit
  -f         Path to proxy configuration file in YAML format

  Proxy:
  -l         Address of HTTP proxy server (Default: "127.0.0.1:8080")
  -s         Address of SOCKS5 proxy server (Default: "127.0.0.1:1080")
  -c         Path to certificate PEM encoded file
  -k         Path to private key PEM encoded file
  -U         User for HTTP proxy (basic auth). This flag invokes prompt for password (not echoed to terminal)
  -u         User for SOCKS5 proxy authentication. This flag invokes prompt for password (not echoed to terminal)
  -i         Bind proxy to specific network interface (either by interface name or index)
  -6         Enable IPv6 support for TCP and UDP
  -socks4    Use SOCKS4/SOCKS4a as the upstream proxy protocol (default: SOCKS5)
  -nohttp    Disable HTTP proxy server
  -nosocks   Disable SOCKS upstream proxy
  -dns       Use custom DNS server (Example: "8.8.8.8" or "2001:4860:4860::8888")

  Logs:
  -d         Show logs in DEBUG mode
  -j         Show logs in JSON format
  -logfile   Log file path (Default: stdout)
  -nocolor   Disable colored output for logs (no effect if -j flag specified)
  -pprof     Address of pprof server with profiling data

  Sniffing:
  -sniff     Enable traffic sniffing for HTTP and TLS
  -snifflog  Sniffed traffic log file path (Default: the same as -logfile)
  -body      Collect request and response body for HTTP traffic (credentials, tokens, etc)
`

const usageExtra string = `
  TProxy:
  -T         Address of transparent proxy server
  -Tu        Address of transparent UDP proxy server
  -M         Transparent proxy mode: (redirect, tproxy, tlocal)
  -w         Number of instances of transparent proxy server (Default: number of CPU cores)
  -wu        Number of instances of transparent UDP proxy server (Default: number of CPU cores)
  -auto      Automatically setup iptables and kernel parameters for transparent proxy (requires elevated privileges)
  -mark      Set mark for each packet sent through transparent proxy (Default: redirect 0, tproxy 100, tlocal 100)
  -P         Comma separated list of ports to ignore when proxying traffic (Example: "22,80,443,9092")
  -dump      Dump iptables rules and other system settings generated by -auto flag

  Spoofing:
  -arpspoof  Enable ARP spoof proxy for selected targets (Example: "targets 10.0.0.1,10.0.0.5-10,192.168.1.*,192.168.10.0/24;fullduplex false;debug true;interval 10s")
  -ndpspoof  Enable NDP spoof proxy for selected targets (Example: "ra true;na true;targets fe80::3a1c:7bff:fe22:91a4;fullduplex false;debug true;interval 10s")

  Packet Capture:
  -pcap      Enable packet capture (Example: "promisc true;expr ip proto tcp;snaplen 65535;timeout 10s;packet_count 100;packet_buffer 8192;exts txt,pcap,pcapng")

  Namespaces:
  -in-netns  Name or path of network namespace for inbound listeners (Default: default namespace)
  -out-netns Name or path of network namespace for outbound connections (Default: default namespace)
`

func root(args []string) error {
	conf := gohpts.Config{}
	flags := flag.NewFlagSet(gohpts.App, flag.ExitOnError)
	addrSocks := flags.String("s", "", "")
	userSocks := flags.String("u", "", "")
	passSocks := ""
	flags.StringVar(&conf.AddrHTTP, "l", "", "")
	flags.StringVar(&conf.ServerUser, "U", "", "")
	flags.StringVar(&conf.CertFile, "c", "", "")
	flags.StringVar(&conf.KeyFile, "k", "", "")
	flags.StringVar(&conf.ServerConfPath, "f", "", "")
	flags.BoolVar(&conf.IPv6Enabled, "6", false, "")
	flags.BoolVar(&conf.SOCKS4Enabled, "socks4", false, "")
	flags.BoolVar(&conf.NoHTTP, "nohttp", false, "")
	flags.BoolVar(&conf.NoSOCKS, "nosocks", false, "")
	flags.StringVar(&conf.DNS, "dns", "", "")
	flags.StringVar(&conf.Interface, "i", "", "")
	flags.BoolFunc("I", "", func(flagValue string) error {
		if err := network.DisplayInterfaces(false); err != nil {
			fmt.Fprintf(os.Stderr, "%s: %v\n", gohpts.App, err)
			os.Exit(2)
		}
		os.Exit(0)
		return nil
	})
	daemon := flags.Bool("D", false, "")
	if slices.Contains(gohpts.SupportedTProxyOS, runtime.GOOS) {
		flags.StringVar(&conf.TProxy, "T", "", "")
		flags.StringVar(&conf.TProxyUDP, "Tu", "", "")
		flags.Func("M", "", func(flagValue string) error {
			if !slices.Contains(gohpts.SupportedTProxyModes, flagValue) {
				fmt.Fprintf(os.Stderr, "%s: %s is not supported (type '%s -h' for help)\n", gohpts.App, flagValue, gohpts.App)
				os.Exit(2)
			}
			conf.TProxyMode = flagValue
			return nil
		})
		flags.UintVar(&conf.TProxyWorkers, "w", 0, "")
		flags.UintVar(&conf.TProxyUDPWorkers, "wu", 0, "")
		flags.BoolVar(&conf.Auto, "auto", false, "")
		flags.UintVar(&conf.Mark, "mark", 0, "")
		flags.StringVar(&conf.ARPSpoof, "arpspoof", "", "")
		flags.StringVar(&conf.NDPSpoof, "ndpspoof", "", "")
		flags.StringVar(&conf.Pcap, "pcap", "", "")
		flags.StringVar(&conf.IgnoredPorts, "P", "", "")
		flags.BoolVar(&conf.Dump, "dump", false, "")
		flags.StringVar(&conf.InNetNS, "in-netns", "", "")
		flags.StringVar(&conf.OutNetNS, "out-netns", "", "")
	}
	flags.StringVar(&conf.LogFilePath, "logfile", "", "")
	flags.BoolVar(&conf.Debug, "d", false, "")
	flags.BoolVar(&conf.JSON, "j", false, "")
	flags.BoolVar(&conf.Sniff, "sniff", false, "")
	flags.StringVar(&conf.SniffLogFile, "snifflog", "", "")
	flags.StringVar(&conf.AddrPprof, "pprof", "", "")
	flags.BoolVar(&conf.NoColor, "nocolor", false, "")
	flags.BoolVar(&conf.Body, "body", false, "")
	flags.BoolFunc("v", "", func(flagValue string) error {
		fmt.Printf("%s (built for %s %s with %s)\n", gohpts.Version, runtime.GOOS, runtime.GOARCH, runtime.Version())
		os.Exit(0)
		return nil
	})

	flags.Usage = func() {
		fmt.Print(usagePrefix)
		if slices.Contains(gohpts.SupportedTProxyOS, runtime.GOOS) {
			fmt.Print(usageExtra)
		}
	}

	if err := flags.Parse(args); err != nil {
		return err
	}
	seen := make(map[string]bool)
	flags.Visit(func(f *flag.Flag) { seen[f.Name] = true })
	if !seen["f"] { // config file allows for overrides, so no point in checking flags here
		if seen["T"] {
			if !seen["M"] {
				return fmt.Errorf("transparent proxy mode is not provided: -M flag")
			}
		}
		if seen["Tu"] {
			if !seen["M"] {
				return fmt.Errorf("transparent proxy mode is not provided: -M flag")
			}
			if conf.TProxyMode != "tproxy" && conf.TProxyMode != "tlocal" {
				return fmt.Errorf(`transparent UDP proxy requires "tproxy" or "tlocal" mode`)
			}
		}
		if seen["socks4"] {
			if seen["Tu"] {
				return fmt.Errorf("-socks4 does not support udp protocol: -Tu flag")
			}
		}

		if seen["M"] {
			if !seen["T"] && !seen["Tu"] {
				return fmt.Errorf("transparent proxy mode requires -T or -Tu flag")
			}
		}
		if seen["w"] {
			if !seen["T"] {
				return fmt.Errorf("-w requires -T flag")
			}
		}
		if seen["wu"] {
			if !seen["Tu"] {
				return fmt.Errorf("-wu requires -Tu flag")
			}
		}
		if seen["ndpspoof"] {
			if !seen["6"] {
				return fmt.Errorf("-ndpspoof requires -6 flag")
			}
		}
		if seen["mark"] {
			if !seen["T"] && !seen["Tu"] {
				return fmt.Errorf("-mark requires -T or -Tu flag")
			}
		}
		if seen["P"] {
			if !seen["auto"] {
				return fmt.Errorf("-P requires -auto flag")
			}
		}
		if seen["dump"] {
			if !seen["auto"] {
				return fmt.Errorf("-dump requires -auto flag")
			}
		}
		if seen["snifflog"] {
			if !seen["sniff"] {
				return fmt.Errorf("-snifflog only works with -sniff flag")
			}
		}
		if seen["body"] {
			if !seen["sniff"] {
				return fmt.Errorf("-body only works with -sniff flag")
			}
		}
	}
	if seen["D"] {
		if seen["u"] || seen["U"] {
			return fmt.Errorf("-u and -U flags do not work in daemon mode")
		}
	}
	if seen["u"] && !seen["socks4"] && !seen["nosocks"] {
		fmt.Print("SOCKS5 Password: ")
		bytepw, err := term.ReadPassword(int(os.Stdin.Fd()))
		if err != nil {
			return err
		}
		passSocks = string(bytepw)
		fmt.Print("\033[2K\r")
	}
	if seen["U"] && !seen["nohttp"] {
		fmt.Print("HTTP Password: ")
		bytepw, err := term.ReadPassword(int(os.Stdin.Fd()))
		if err != nil {
			return err
		}
		conf.ServerPass = string(bytepw)
		fmt.Print("\033[2K\r")
	}
	conf.SocksProxy = []gohpts.ProxyEntry{{Address: *addrSocks, Username: *userSocks, Password: passSocks}}
	if *daemon {
		if os.Getenv("GOHPTS_DAEMON") != "1" {
			env := os.Environ()
			files := [3]*os.File{}
			env = append(env, "GOHPTS_DAEMON=1")
			files[0], _ = os.Open(os.DevNull)
			files[1], _ = os.Open(os.DevNull)
			files[2], _ = os.Open(os.DevNull)
			attr := &os.ProcAttr{
				Files: []*os.File{
					files[0], // stdin
					files[1], // stdout
					files[2], // stderr
				},
				Dir: ".",
				Env: env,
			}
			path, err := os.Executable()
			if err != nil {
				return err
			}
			process, err := os.StartProcess(
				path,
				os.Args,
				attr,
			)
			if err != nil {
				return err
			}
			fmt.Printf("%s pid: %d\n", gohpts.App, process.Pid)
			process.Release()
			os.Exit(0)
		}
	}
	p, err := gohpts.New(&conf)
	if err != nil {
		return err
	}
	return p.Run()
}
